name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: decode SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem
      
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: private_key.pem
          port: 22
          source: "./*"
          target: "/usr/share/nginx/html"
          overwrite: true
          strip_component: 0
          debug: true
          disable_strict_host_key_checking: true
          
      - name: Restart ngnix
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: private_key.pem
          script: |
           sudo systemctl restart nginx
          
